"""create authors and items tables

Revision ID: 79b61e06e32b
Revises: 
Create Date: 2026-06-17 03:14:36.246891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b61e06e32b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('karma', sa.Integer(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('created_utc', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('STORY', 'COMMENT', 'JOB', 'POLL', 'POLLOPT', name='itemtype'), nullable=False),
    sa.Column('by', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('feed_type', sa.Enum('TOP', 'NEW', 'BEST', 'ASK', 'SHOW', 'JOB', name='feedtype'), nullable=True),
    sa.Column('created_utc', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('dead', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['by'], ['authors.username'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('authors')
    # ### end Alembic commands ###
